version: '3'
services:
  ml_Spark_notebook:
    image: ml_spark
    user: "${UID}:${GID}"
    build: .
    environment:
        JUPYTER_ENABLE_LAB: 1
        NB_USER: raza
        NB_GID: 1000
        CHOWN_HOME: 'yes'
        CHOWN_HOME_OPTS: '-R'
    volumes:
      - ./notebooks/:/home/jovyan/notebooks/
    ports:
      - 8888:8888
